### ISSUE TITLE
Add check for 0x3 tx support instead of relying on a special flag

### ISSUE THREAD

**Issue by parithosh** [MariusVanDerWijden/tx-fuzz#29]

**Comment by radkomih** [comment]
I am participating in the Ethereum Protocol Fellowship and am interested in enhancing existing fuzzing tools. Could you provide more details on this? Additionally, are there any other issues I could potentially work on?

**Comment by parithosh** [comment]
Hi, this issue is no longer relevant and I'll be closing it. The 0x03 tx support was split out and made into its own command in this PR: https://github.com/MariusVanDerWijden/tx-fuzz/pull/30

The approach taken was more linux style, so rather than adding custom logic the tool will rely on its caller to ensure that 0x03 txs are supported when said flag is used. More details here: https://github.com/MariusVanDerWijden/tx-fuzz/pull/30#issuecomment-1696259657
