### ISSUE TITLE
Increase likelihood of generating any transaction data

### ISSUE THREAD

**Issue by remoterami** [MariusVanDerWijden/tx-fuzz#34]
When generating random transactions with `livefuzzer spam`, I'm having issues generating random transaction data. After changing some logic to skip all the rpc interactions and just let it generate [code](https://github.com/MariusVanDerWijden/tx-fuzz/blob/master/transactions.go#L59), it takes multiple minutes to find anything other than 0 bytes of data. I don't think this is intended.. But I could also be missing something of course.

**Comment by MariusVanDerWijden** [comment]
Ahh nvm I found the bug, the mutateBytes will not prefill the array, so it is almost completely empty. Will fix, thanks!

**Comment by MariusVanDerWijden** [comment]
fixed by https://github.com/MariusVanDerWijden/tx-fuzz/commit/a093b24e911894a58217b05e0fd05904ee82456e
Thanks for reporting!

**Comment by remoterami** [comment]
Thanks for fixing :+1:
Just fyi, looking at it it should be the same for [blobs](https://github.com/MariusVanDerWijden/tx-fuzz/blob/master/cmd/livefuzzer/blob.go#L32-L34)

**Comment by MariusVanDerWijden** [comment]
Thanks, I completely rewrote that part in order to get rid of the code duplication: https://github.com/MariusVanDerWijden/tx-fuzz/pull/37
